# name: WordPress CI/CD

# on:
#   push:
#     branches:
#       - gh-page
#   pull_request:
#     branches:
#       - gh-page

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:5.7
#         options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
#         env:
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_DATABASE: wordpress_test
#         ports:
#           - 3306:3306

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '7.4'
#         extensions: mbstring, mysqli, intl, xml, curl, json, ctype, token_get_all, fileinfo
#         ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
#         coverage: none

#     # - name: Install Composer dependencies
#     #   run: composer install --no-progress --prefer-dist

#     - name: Copy wp-config.php
#       run: cp wp-config-sample.php wp-config.php

#     - name: Update wp-config.php
#       run: |
#         sed -i "s/database_name_here/wordpress_test/" wp-config.php
#         sed -i "s/username_here/root/" wp-config.php
#         sed -i "s/password_here/root/" wp-config.php
#         echo "define('WP_DEBUG', true);" >> wp-config.php
#         echo "define('WP_DEBUG_LOG', true);" >> wp-config.php


name: Deploy WordPress Static Site to GitHub Pages

on:
  push:
    branches:
      - gh-page
  pull_request:
    branches:
      - gh-page

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, mysqli, intl, xml, curl, json, ctype, token_get_all, fileinfo
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
        coverage: none

    - name: Copy wp-config.php
      run: cp wp-config-sample.php wp-config.php

    - name: Update wp-config.php
      run: |
        sed -i "s/database_name_here/wordpress_test/" wp-config.php
        sed -i "s/username_here/root/" wp-config.php
        sed -i "s/password_here/root/" wp-config.php
        sed -i "s/localhost/127.0.0.1:3306/" wp-config.php
        echo "define('WP_DEBUG', true);" >> wp-config.php
        echo "define('WP_DEBUG_LOG', true);" >> wp-config.php

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Install WordPress
      run: |
        wp core install --url="http://localhost" --title="Test Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com"
        wp plugin install simply-static --activate

    - name: Generate Static Site
      run: |
        wp simply-static generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wp-content/uploads/simply-static
