name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-page  # Thay đổi tên branch nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, zip, curl, openssl
          
      - name: Install Simply Static CLI
        run: curl -sLO https://github.com/simply-static/simply-static/releases/latest/download/simply-static.phar
      
      - name: Make Simply Static executable
        run: chmod +x simply-static.phar
      
      - name: Generate static site
        run: ./simply-static.phar export --url="http://your-wordpress-site-url"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
