name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-page  # Thay đổi tên branch nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, zip, curl, openssl
          
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
        
      - name: Install Simply Static
        run: composer require wpsimplestatic/wpsimplestatic-cli
        
      - name: Generate static site
        run: vendor/bin/wpsimplestatic export
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
